#!/bin/bash
echo killing old ffmpegs

PID=( $(ps -e | grep ffmpeg | awk '{print $1;}'))
if [ $? = 1 ];then
echo "error getting ffmpeg PID, exiting"
exit
fi
if [ ! -n "$PID" ];then
PID=1234567
fi
echo killing ffmpeg with PID $PID
kill $PID

echo starting ffmpeg
#ffmpeg -re -f jack -i ffmpeg -acodec ogg -ab 32k -ac 1 -f rtp rtp://192.168.0.254:1234
ffmpeg -f jack -i ffmpeg -f rtp rtp://127.0.0.1:1234  > ffmpeg/stream.sdp

FF=$!
echo ffmpeg started with PID $FF

exit